boolean-uk/team-dev-client-team-3

.eslintrc.json
Changes made in `.eslintrc.json`.
=> Issue(#14): Added ESlint rule.

.github/workflows/linter.yml
A part of the GitHub actions framework.
Set up to run on a push or PR. Uses the linter installed in the project.
Note: might want to force a fail when violations exceeds 0.
=> Issue(#12): Created GitHub Action that lints the project on push/pr. 

src/components/form/textInput/index.js, src/pages/login/index.js
Moved the snippet:
```js
<div className="passwordActionContainer">
<div className="passwordActionBox" style={{ textAlign: 'left' }}>
{/* Remember me here? */}
</div>
<a
className="passwordActionBox"
style={{ textAlign: 'right' }}
href="https://youtu.be/dQw4w9WgXcQ"
>
Forgot password?
</a>
</div>
```
From `src/components/form/textInput/index.js` to `src/pages/login/index.js` to solve the issue.
=> Issue(#27): Moved `Forgot password?`-link from textinput to loginview.

src/pages/register/index.js, src/pages/register/register.css, src/styles/_globals.css
Someone review my amazing code, please 💯
=> Added text info on register page. Closing issue #8

src/pages/welcome/index.js, src/pages/welcome/stepFour/index.js, src/pages/welcome/stepTwo/index.js
Added the second step of the registration form and moved step four (it was wrongly placed and named by Boolean UK).
Current look:
=> Issue(#23): Added step two to Create Profile and moved step four

src/pages/welcome/index.js, src/pages/welcome/stepTwo/index.js
Added the fourth step to create profile user flow.
Changed a label `label={'Password *'}` -> `label={'Password*'}`.
~~This PR is upstream from PR #44 and will therefore have the same changes as #44 made (this PR should accurately reflect the changes made when #44 is merged).~~
~~tldr; accept #44 then this.~~
=> Issue(#25): Step four in Create Profile flow

src/pages/login/index.js
In an earlier commit I moved the submit button in src/pages/login/index.js from outside the form to inside the form.
This caused unintended consequences that broke the login page.
This PR moves the button back outside the form.
=> Fixed the bug I cause :(((

src/components/form/textInput/index.js, src/pages/register/index.js, src/pages/register/register.css
Still need to implement backend validation for security.
=> Local email and password validation now works.

src/pages/register/index.js, src/pages/register/registrationValidation.js, src/service/apiValidation.js
Validation methods previously in `src/pages/register/index.js` has been moved to `src/pages/register/registrationValidation.js`.
`src/service/apiValidation.js` contains methods to interact with the validation endpoint.
Main functionality resides in `src/pages/register/index.js`.
Note: we should create an issue on showing the errors to the user.
=> Register: Validation of password and email with backend, and a refactor.

package-lock.json, package.json, src/components/createPostModal/index.js, src/components/createPostModal/style.css, src/components/editPostModal/index.js, src/components/modal/index.js, src/components/modal/style.css, src/components/post/index.js, src/components/post/style.css, src/components/posts/index.js, src/components/profileCircle/index.js, src/context/auth.js, src/pages/cohort/CohortPage.jsx, src/pages/dashboard/index.js
Able to edit and delete posts, also minor styling changes
=> 55 frontend   post UI card

src/components/createPostModal/index.js, src/components/editPostModal/index.js, src/components/header/index.js, src/components/post/index.js, src/components/post/style.css, src/components/posts/index.js, src/context/auth.js, src/pages/dashboard/index.js
When posting the incorrect user was used displaying NaN. Instead use the user stored in localstorage. Also updated places where user was static to instead use localstorage. 
If the header-card is open, it will automatically close if the user clicks outside of the header-card
=> (Issue#89): Fixed NaN when posting (+ some other minor stuff)

src/components/createPostModal/index.js, src/components/credentials/index.js, src/components/profileCircle/index.js, src/context/auth.js, src/pages/cohort/CohortPage.jsx, src/pages/login/index.js
When login fails (back-end returns 4XX), the error returned by back-end is displayed.
Notes: should probably validate the login client-side so that so that people cant Dos-attack us by just trying to log-in.
=> Issue(#72): Implement feedback when trying to login with bad credentials.

src/components/avatarList/index.jsx, src/components/avatarList/singleLineListItem/index.jsx, src/components/avatarList/singleLineListItem/style.css, src/components/avatarList/style.css, src/pages/dashboard/index.js, src/pages/dashboard/testData.jsx
**What**
Created the AvatarList component described [here](https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy--Cohort-Manager-app---Designs?node-id=365-17212&t=Fx2hJQkVgbH6WHYn-4) and [here](https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy--Cohort-Manager-app---Designs?node-id=405-17582&t=Fx2hJQkVgbH6WHYn-4).
Also, I added some test data here `src/pages/dashboard/testData.jsx`, while back end creates endpoint in issue #x (edit when you remember to create back-end issue).
Currently there is no support for [double line list items](https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy--Cohort-Manager-app---Designs?node-id=405-17582&t=Fx2hJQkVgbH6WHYn-4).
**Results**
| Actual    | Figma |
| -------- | ------- |
| <img width="463" height="499" alt="image" …
=> Issue(#68): Created a component that displays all other users in the userss cohort.

src/components/createPostModal/index.js, src/components/form/index.js, src/components/form/textInput/index.js, src/components/post/index.js, src/components/profileCircle/index.js, src/context/auth.js, src/pages/dashboard/index.js, src/pages/profile/ProfilePage.jsx, src/pages/profile/style.css, src/pages/welcome/index.js, src/service/apiClient.js
The user can go on profilepage and change their profile. Once saved the user is redirected to the home page
=> (Issue#98): frontend   update profilepage to use user from localstorage

src/App.js, src/components/stepper/style.css, src/context/auth.js
https://github.com/boolean-uk/team-dev-client-team-3/issues/166
Test:
- Make sure already registered users who have completed the "Create profile" steps cannot visit the `/welcome` page.
- Make sure newly registered users still can access `/welcome` page as usual
=> 166 restrict welcome page

src/components/credentials/index.js, src/pages/login/index.js
…d away the "forgot password" link in login index.js.
The code for both still exists as comments to possibly be implemented in the future.
=> (Issue#181): Remove unused UI elements (forgot password, etc.)

src/assets/fullLogo.js, src/components/header/index.js, src/components/navigation/index.js, src/components/navigation/style.css, src/context/auth.js, src/pages/welcome/stepBasic/index.js
#192 
* User cannot change link in signup
* ProfileCircle appears in Header after signup
=> (Issue#192) User cannot change link inside signup

src/context/auth.js
Fix
- Add redirect to login when there is no token in local storage
- Set isAuthLoading when user state changes via useEffect to avoid redundant code
=> Add redirect to login when no token in local storage

src/components/button/index.js, src/components/cohorts/cohortListItem/index.js, src/components/cohorts/index.js, src/components/students/index.js, src/components/teachers/index.js, src/pages/cohort/CohortPage.jsx, src/styles/_buttons.css
#195 
* Buttons are only visual
* Select cohort to see users
* Teachers card not included in figma but might be nice to have?
* Continue on #196 to get actual cohorts and users
=> (Issue#195): Simple skeleton for teacherview cohorts

test/helpers.ts, test/profilePage.spec.ts
See the changes. Added a couple of awaits.
=> A couple of expects should be awaited

src/pages/register/index.js, src/pages/register/registrationValidation.js
Changes:
- Adds error message if user try to register with email that exists in database
- Message is reset when Register button is clicked
=> 232 frontend   signup error message

src/pages/login/index.js
Changes:
- Error message is cleared on an onChange event
- Added loading animation on log in button to prevent multiple clicks
=> 231 frontend   remove invalid email message on login page

src/components/stepper/index.js, src/components/stepper/style.css
Changes:
- Adds button "Finish Later" on Welcome page. Clicking it will log out the user.
=> 254 frontend   stuck on profile creation

src/pages/cohort/CohortPage.jsx
Cohort button should work
No cohorts available fix
=> fixed add cohort button
